Features/sub/zrest loading
clovirtualfashion/closet.viewer.js pull request #95
Opened 2020-12-15 08:38 UTC by CLO-Tkay

- SRest 파일 parsing 부분 refactoring

2020-12-15 11:24 UTC, ingun37 requested changes
closet viewer 클래스가 특정 함수들이 구현돼있어야 테스트랑 벤치마킹이 가능한데, 구현부분도 같이 제거하셨더라고요. 그부분 다시 추가해주세요

2020-12-15 11:24 UTC, ingun37 commented on src/viewer.js
> -import { capturePrincipleViews, recursiveObjectwiseViewFrustumCulling } from "./lib/clo/utils/PrincipleViews";
빌드된 closet.viewer.js에 위 함수가 구현이 돼있어야 테스트가 가능합니다.

2020-12-15 11:24 UTC, ingun37 commented on src/viewer.js
> -
이부분도 마찬가지고요

2020-12-15 11:24 UTC, ingun37 commented on src/viewer.js
> -  }
이부분 다시 추가하셔야 하고요

2020-12-15 11:24 UTC, ingun37 commented on src/viewer.js
> -    return countRenderingUsingRenderTarget(this.scene, this.object3D, timeInMS, {width, height});
이부분도 추가하셔야 ㅎ ㅐ요

2020-12-15 11:25 UTC, ingun37 commented
코드리뷰 첫 태클 🥊🥊🥊

2020-12-16 00:02 UTC, CLO-Tkay commented
@ingun37 추가했어요ㅎㅎ

2020-12-16 02:17 UTC, ingun37 approved these changes

2020-12-16 02:50 UTC, merged